### PR TITLE
Change to CMSDAS env.

### PR DESCRIPTION
**Pull request by geonmo**
CMSDAS환경에 맞도록 디렉토리를 수정하였습니다.

### CODE REVIEW

**Comment by geonmo** [comment]
@monttj Could you merge this PR for CMSDAS?

**Comment by monttj** [comment]
Thank you for taking a look and updating! Just one question, is this file also available at the same location at the kisti machine? 

If it is not the same path, we need separate two file lists for kisti and knu?

**Comment by geonmo** [comment]
Ah, this PR does not working at KISTI. Ok, I will fix it.

**Comment by monttj** [comment]
we can make "knu" directory under sourceFiles directory and put those files there?

**Comment by geonmo** [comment]
OK, I will.

**Comment by geonmo** [comment]
@monttj Could you re-check this PR?

**Comment by monttj** [comment]
Great! Thank you very much!

**Pull request merged**
