### PR TITLE
Add v7-3-6 samples.

### PR DESCRIPTION
**Pull request by geonmo**
Change to v7-3-6 data lists.

### CODE REVIEW

**Comment by monttj** [comment]
Ah, it is not same data set with 50 ns as before ?

**Comment by monttj** [comment]
we finished our exercise with 46 pb-1 luminosity, is it corresponding to which luminosity?

**Comment by geonmo** [comment]
As I know, it is same dataset. Just CATTools version was changed.

**Comment by monttj** [comment]
So it is splitting more files because it was only four files before.

**Comment by geonmo** [comment]
I checked TT sample's event number. It is exactly same before. I think it is just crab configuration difference or to solve memory leak problem at v7-3-5. This memory leak problem is now solved at v7-3-6.

**Comment by monttj** [comment]
Did you also update the source txt files at KISTI?

**Comment by geonmo** [comment]
Ah, OK. I will.

**Comment by monttj** [comment]
Thank you!

**Pull request merged**
